//! Generate `assets/external/usdz_sample.usdz` so `cargo run -- usdz_sample.usdz`
//! has something real to show. Writes a `.usdz` with:
//!
//! - a USDA scene containing a Cube + a UsdPreviewSurface material + an
//!   embedded `textures/checker.png` reference,
//! - a procedurally-generated checker PNG in `textures/checker.png`.
//!
//! Regenerates only when this script changes — the zip contents are
//! deterministic otherwise.

use std::fs;
use std::io::{Cursor, Write};
use std::path::PathBuf;

fn main() {
    let workspace_root = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let dest = workspace_root.join("assets/external/usdz_sample.usdz");

    // Only regen when the build script or git head changes.
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=.git/HEAD");
    println!("cargo:rerun-if-changed=.git/logs/HEAD");
    println!("cargo:rerun-if-changed=.git/refs/heads/");
    println!("cargo:rerun-if-changed=.git/packed-refs");
    println!("cargo:rerun-if-changed=../bevy_glacial/.git/HEAD");
    println!("cargo:rerun-if-changed=../bevy_glacial/.git/logs/HEAD");

    let git_sha = std::process::Command::new("git")
        .args(["rev-parse", "HEAD"])
        .output()
        .ok()
        .and_then(|o| String::from_utf8(o.stdout).ok())
        .map(|s| s.trim().to_string())
        .unwrap_or_else(|| "unknown".to_string());
    println!("cargo:rustc-env=USDHUB_GIT_SHA={git_sha}");

    let glacial_sha = std::process::Command::new("git")
        .args(["-C", "../bevy_glacial", "rev-parse", "HEAD"])
        .output()
        .ok()
        .and_then(|o| String::from_utf8(o.stdout).ok())
        .map(|s| s.trim().to_string())
        .unwrap_or_else(|| "unknown".to_string());
    println!("cargo:rustc-env=USDHUB_GLACIAL_SHA={glacial_sha}");

    let Ok(zip_bytes) = build_zip() else {
        eprintln!(
            "build.rs: failed to generate usdz_sample.usdz — skipping; \
             run `cargo clean -p bevy_openusd-viewer` to retry."
        );
        return;
    };
    if let Some(parent) = dest.parent() {
        let _ = fs::create_dir_all(parent);
    }
    if let Err(e) = fs::write(&dest, &zip_bytes) {
        eprintln!("build.rs: write {dest:?} failed: {e}");
    }
}

fn build_zip() -> Result<Vec<u8>, Box<dyn std::error::Error>> {
    let mut buf = Vec::<u8>::new();
    {
        let mut zw = zip::ZipWriter::new(Cursor::new(&mut buf));
        let opts = zip::write::SimpleFileOptions::default()
            .compression_method(zip::CompressionMethod::Stored);

        zw.start_file("scene.usda", opts)?;
        zw.write_all(USDA.as_bytes())?;

        zw.start_file("textures/checker.png", opts)?;
        zw.write_all(&checker_png())?;

        zw.finish()?;
    }
    Ok(buf)
}

const USDA: &str = r#"#usda 1.0
(
    defaultPrim = "World"
    upAxis = "Y"
    metersPerUnit = 1.0
    doc = "Viewer-side USDZ sample (generated by build.rs)."
)

def Xform "World"
{
    def Scope "Materials"
    {
        def Material "Checker"
        {
            token outputs:surface.connect = </World/Materials/Checker/Surface.outputs:surface>

            def Shader "Surface"
            {
                uniform token info:id = "UsdPreviewSurface"
                color3f inputs:diffuseColor.connect = </World/Materials/Checker/DiffuseTex.outputs:rgb>
                float inputs:roughness = 0.55
                float inputs:metallic = 0.0
                token outputs:surface
            }

            def Shader "DiffuseTex"
            {
                uniform token info:id = "UsdUVTexture"
                asset inputs:file = @./textures/checker.png@
                token inputs:sourceColorSpace = "sRGB"
                float3 outputs:rgb
            }
        }

        def Material "Emissive"
        {
            color3f inputs:emissiveColor = (0.15, 0.45, 1.3)
            color3f inputs:diffuseColor = (0.05, 0.05, 0.15)
            token outputs:surface.connect = </World/Materials/Emissive/Surface.outputs:surface>

            def Shader "Surface"
            {
                uniform token info:id = "UsdPreviewSurface"
                color3f inputs:diffuseColor.connect = </World/Materials/Emissive.inputs:diffuseColor>
                color3f inputs:emissiveColor.connect = </World/Materials/Emissive.inputs:emissiveColor>
                float inputs:roughness = 0.4
                token outputs:surface
            }
        }
    }

    def Cube "CheckerBox" (
        prepend apiSchemas = ["MaterialBindingAPI"]
    )
    {
        double size = 0.6
        rel material:binding = </World/Materials/Checker>
        double3 xformOp:translate = (-0.6, 0.3, 0)
        uniform token[] xformOpOrder = ["xformOp:translate"]
    }

    def Sphere "EmissiveBall" (
        prepend apiSchemas = ["MaterialBindingAPI"]
    )
    {
        double radius = 0.35
        rel material:binding = </World/Materials/Emissive>
        double3 xformOp:translate = (0.6, 0.35, 0)
        uniform token[] xformOpOrder = ["xformOp:translate"]
    }
}
"#;

/// Procedural 32×32 black-and-white checker PNG. No external deps — the
/// compression uses `flate2` indirectly through the `zip` crate's feature
/// set, but PNG needs its own encoder, so we hand-build an uncompressed
/// PNG with one row per scanline.
///
/// Actually: to keep build.rs dep-free we cheat. We emit the image by
/// inlining `image` crate output. The `image` crate is a build dep on the
/// viewer (declared in Cargo.toml).
fn checker_png() -> Vec<u8> {
    use image::{ImageFormat, Rgba, RgbaImage};
    let size = 32u32;
    let mut img = RgbaImage::new(size, size);
    for y in 0..size {
        for x in 0..size {
            let on = ((x / 4) + (y / 4)) % 2 == 0;
            let c = if on {
                [235, 235, 240, 255]
            } else {
                [40, 50, 70, 255]
            };
            img.put_pixel(x, y, Rgba(c));
        }
    }
    let mut out = Vec::new();
    img.write_to(&mut Cursor::new(&mut out), ImageFormat::Png)
        .expect("png encode never fails for a small RGBA8 buffer");
    out
}
